### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by bogachenko** [uBlock-user/uBO-Scriptlets#1]
I will ask how to add the official list of scriptlets and yours? (no way)

**Comment by uBlock-user** [comment]
Why are you asking that here ? This isn't the place to ask that.

**Comment by bogachenko** [comment]
I asked (how do you use) how can I use 2 different sources, and at the same time wrote an idea for an update...

**Comment by uBlock-user** [comment]
https://github.com/uBlock-user/uBO-Scriptlets#installation

**Comment by uBlock-user** [comment]
@bogachenko https://github.com/uBlockOrigin/uBlock-issues/issues/226

Is that what you mean ?

**Comment by bogachenko** [comment]
YEAH

**Comment by uBlock-user** [comment]
not right now as it's not possible in uBO. There's that FR for that. if gorhill adds such functionality.

**Comment by bogachenko** [comment]
блять

**Comment by bogachenko** [comment]
Well, the proposal of that dude was on September 12 last year .. burned did not respond .. I will not be able to see this function, since he probably did not add it. Sadly

**Comment by uBlock-user** [comment]
He hasn't declined it, so it will take a while.

**Comment by uBlock-user** [comment]
Fixed in 1.18.17b6

**Comment by bogachenko** [comment]
nice!
