### ISSUE TITLE
voe.sx

### ISSUE THREAD

**Issue by ghajini** [uBlock-user/uBO-Scriptlets#12]
@uBlock-user 
`https://voe.sx/7hehhxk5aoto`
will you see what happened for download button on this site,clicking on that ,closed by easylist filter can do
```
||3r1kwxcd.top^$popup,badfilter
||3r1kwxcd.top^$badfilter
```

but then clicking on download results in popups ,redirection to ads(you need to close new window ,sometimes ads window come and sometimes download file window)

,console shows
![Screenshot (254)](https://user-images.githubusercontent.com/20338483/112321869-6debec00-8cd6-11eb-968f-e1d85220d990.png)

**Comment by uBlock-user** [comment]
Is the download not happening ?

```
voe.sx##+js(nowoif, /^/, 2)
*$frame,redirect-rule=noopframe,domain=voe.sx
```

does that help ?

**Comment by uBlock-user** [comment]
```
function download_file() {
  let code = '7hehhxk5aoto';
  let quality = 'n';
  let hash = '1419585-103-241-1616595406-573e3903a61b9072e1f21b8de003f123';
  var ca760df91aa72f469badd2dbb2fa1dd3 = ['i2zMzMzMzG', 'Bg9JyxrPB24', 'Ahr0Chm6lY92B2uUC3GVzgW/B3a9zg93BMXVywrFB3jPzYzPzd1ICMvHAYnIDg9H', 'yM9KEq', 'mJCXnZrvuNrSy04', 'muL6vwDPwG', 'zxHLyW', 'yxrVyG', 'jMHHC2G9', 'z2v0qxr0CMLIDxrL', 'BgLUAW', 'mZK0ndiYogjLtvnpvW', 'CMvWBgfJzunOAwXK', 'Ahr0Chm6lY92B2uUC3GVzgW/B3a9zg93BMXVywrFB3jPzYzRzxK9C3vTBwvYjMLKpq', 'z2v0rwXLBwvUDhncEvrHz05HBwu', 'y29UDgvUDa', 'AhjLzG', 'BMfTzq', 'vw5MB3j0Dw5HDgvSEsWGEw91CIbICM93C2vYigjSB2nRCYb0AguGzg93BMXVywqGzNvUy3rPB24SiguUzY4GyNKGyw4GywrIBg9JA2vYlG', 'mtmWodu1mKXSrerJBG', 'ChjLy29UBMvJDa', 'B3bLBG', 'mJi2nZG1DLHjthfN', 'mtfrrgPWvem', 'mty4mdeWmejisvz1Eq', 'DgHLBwuTy29SB3i', 'mtm3mdCXnvv1swjmBW', 'AgvHza', 'BxnHChbSAwnHDgLVBI1uAwXLq29SB3i', 'ndG2nZaXq1vouuvw', 'y3jLyxrLrwXLBwvUDa', 'zNjVBunOyxjdB2rL', 'Ahr0CdOVl2u2mwm4ywqXywqUEhL6', 'yNrVyq', 'Bwv0yq', 'jMrVBwfPBJ0ZCJfRD3HJzc50B3a', 'BgLUAY5OCMvM', 'BgvUz3rO', 'ywrKrxzLBNrmAxn0zw5LCG', 'jM1Vzgu9', 'Ahr0Chm6lY8ZCJfRD3HJzc50B3aVyMnIBwL4AJrWmZ9KB3DUBg9Hzd03nde3odC2yZmWmMfImdzHmZy5mJLLoczWDwjFBw9UzxrPEMvYptu2otbJmJeWnZqXnZG3nMmZmdjHyJa2ytm2oti5ztGXjMnFAwq9nty5mgmYmta3nde3odC2yZmWmMfImdzHmZy5mJLLodeMywrFy29Kzt01nJKWyZiXmdC0mtC4nZzJmZaYywiWnMeZnJKYowu4mszRzxK9nty5mgmYmta3nde3odC2yZmWmMfImdzHmZy5mJLLodeMBw9Kzt1T'];
  var b1eefa4cbdac047203c1fec1b583c61e = function(fad59e9fc3289a13ea5819b497fe8432, af9689a33c06bb92ee2144ac306659ed) {
    fad59e9fc3289a13ea5819b497fe8432 = fad59e9fc3289a13ea5819b497fe8432 - 0x1af;
    var cb1c985f8a4c07cfc745d988ecb219b7 = ca760df91aa72f469badd2dbb2fa1dd3[fad59e9fc3289a13ea5819b497fe8432];
    if (b1eefa4cbdac047203c1fec1b583c61e['ZLjfRu'] === undefined) {
      var ebdc175a6ea80fd165c3b66f7e4ffcea = function(Af9689a33c06bb92ee2144ac306659ed) {
        var C947f8f4dd01bde06249109c537531a9 = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789+/=';
        var Fad59e9fc3289a13ea5819b497fe8432 = '';
        for (var C1cf294adf2717fd0fc08dbe585d2c5d = 0x0, Cb1c985f8a4c07cfc745d988ecb219b7, Ca760df91aa72f469badd2dbb2fa1dd3, A0d91607fc93ff7e5567e840580fe9d6 = 0x0; Ca760df91aa72f469badd2dbb2fa1dd3 = Af9689a33c06bb92ee2144ac306659ed['charAt'](A0d91607fc93ff7e5567e840580fe9d6++); ~Ca760df91aa72f469badd2dbb2fa1dd3 && (Cb1c985f8a4c07cfc745d988ecb219b7 = C1cf294adf2717fd0fc08dbe585d2c5d % 0x4 ? Cb1c985f8a4c07cfc745d988ecb219b7 * 0x40 + Ca760df91aa72f469badd2dbb2fa1dd3 : Ca760df91aa72f469badd2dbb2fa1dd3, C1cf294adf2717fd0fc08dbe585d2c5d++ % 0x4) ? Fad59e9fc3289a13ea5819b497fe8432 += String['fromCharCode'](0xff & Cb1c985f8a4c07cfc745d988ecb219b7 >> (-0x2 * C1cf294adf2717fd0fc08dbe585d2c5d & 0x6)) : 0x0) {
          Ca760df91aa72f469badd2dbb2fa1dd3 = C947f8f4dd01bde06249109c537531a9['indexOf'](Ca760df91aa72f469badd2dbb2fa1dd3);
        }
        return Fad59e9fc3289a13ea5819b497fe8432;
      };
      b1eefa4cbdac047203c1fec1b583c61e['owbaoM'] = function(B1eefa4cbdac047203c1fec1b583c61e) {
        var Ebdc175a6ea80fd165c3b66f7e4ffcea = ebdc175a6ea80fd165c3b66f7e4ffcea(B1eefa4cbdac047203c1fec1b583c61e);
        var b1Eefa4cbdac047203c1fec1b583c61e = [];
        for (var aF9689a33c06bb92ee2144ac306659ed = 0x0, cA760df91aa72f469badd2dbb2fa1dd3 = Ebdc175a6ea80fd165c3b66f7e4ffcea['length']; aF9689a33c06bb92ee2144ac306659ed < cA760df91aa72f469badd2dbb2fa1dd3; aF9689a33c06bb92ee2144ac306659ed++) {
          b1Eefa4cbdac047203c1fec1b583c61e += '%' + ('00' + Ebdc175a6ea80fd165c3b66f7e4ffcea['charCodeAt'](aF9689a33c06bb92ee2144ac306659ed)['toString'](0x10))['slice'](-0x2);
        }
        return decodeURIComponent(b1Eefa4cbdac047203c1fec1b583c61e);
      }, b1eefa4cbdac047203c1fec1b583c61e['MYFYbs'] = {}, b1eefa4cbdac047203c1fec1b583c61e['ZLjfRu'] = !![];
    }
    var a0d91607fc93ff7e5567e840580fe9d6 = ca760df91aa72f469badd2dbb2fa1dd3[0x0],
      c1cf294adf2717fd0fc08dbe585d2c5d = fad59e9fc3289a13ea5819b497fe8432 + a0d91607fc93ff7e5567e840580fe9d6,
      c947f8f4dd01bde06249109c537531a9 = b1eefa4cbdac047203c1fec1b583c61e['MYFYbs'][c1cf294adf2717fd0fc08dbe585d2c5d];
    return c947f8f4dd01bde06249109c537531a9 === undefined ? (cb1c985f8a4c07cfc745d988ecb219b7 = b1eefa4cbdac047203c1fec1b583c61e['owbaoM'](cb1c985f8a4c07cfc745d988ecb219b7), b1eefa4cbdac047203c1fec1b583c61e['MYFYbs'][c1cf294adf2717fd0fc08dbe585d2c5d] = cb1c985f8a4c07cfc745d988ecb219b7) : cb1c985f8a4c07cfc745d988ecb219b7 = c947f8f4dd01bde06249109c537531a9, cb1c985f8a4c07cfc745d988ecb219b7;
  };
  var Ca760dF91aa72f469badd2dbb2fa1dd3 = b1eefa4cbdac047203c1fec1b583c61e,
    EbdC175a6ea80fd165c3b66f7e4ffcea = b1eefa4cbdac047203c1fec1b583c61e;
  (function(cb1c985F8a4c07cfc745d988ecb219b7, C1cf294Adf2717fd0fc08dbe585d2c5d) {
    var Cb1c985F8a4c07cfc745d988ecb219b7 = b1eefa4cbdac047203c1fec1b583c61e,
      B1eeFa4cbdac047203c1fec1b583c61e = b1eefa4cbdac047203c1fec1b583c61e;
    while (!![]) {
      try {
        var C947f8f4Dd01bde06249109c537531a9 = parseInt(Cb1c985F8a4c07cfc745d988ecb219b7('0x1ba')) + parseInt(B1eeFa4cbdac047203c1fec1b583c61e('0x1bf')) + -parseInt(B1eeFa4cbdac047203c1fec1b583c61e('0x1d4')) * -parseInt(Cb1c985F8a4c07cfc745d988ecb219b7('0x1be')) + parseInt(Cb1c985F8a4c07cfc745d988ecb219b7('0x1c1')) + -parseInt(B1eeFa4cbdac047203c1fec1b583c61e('0x1bd')) + -parseInt(B1eeFa4cbdac047203c1fec1b583c61e('0x1c4')) * -parseInt(B1eeFa4cbdac047203c1fec1b583c61e('0x1d5')) + -parseInt(B1eeFa4cbdac047203c1fec1b583c61e('0x1b2'));
        if (C947f8f4Dd01bde06249109c537531a9 === C1cf294Adf2717fd0fc08dbe585d2c5d) break;
        else cb1c985F8a4c07cfc745d988ecb219b7['push'](cb1c985F8a4c07cfc745d988ecb219b7['shift']());
      } catch (Fad59E9fc3289a13ea5819b497fe8432) {
        cb1c985F8a4c07cfc745d988ecb219b7['push'](cb1c985F8a4c07cfc745d988ecb219b7['shift']());
      }
    }
  }(ca760df91aa72f469badd2dbb2fa1dd3, 0xedc91));
  try {
    function gone() {}
    var _0x16d = window[Ca760dF91aa72f469badd2dbb2fa1dd3('0x1c8')](String[Ca760dF91aa72f469badd2dbb2fa1dd3('0x1c6')](0x68, 0x74, 0x74, 0x70, 0x73, 0x3a, 0x2f, 0x2f, 0x76, 0x6f, 0x65, 0x2e, 0x73, 0x78, 0x2f, 0x64, 0x6c, 0x3f, 0x6f, 0x70, 0x3d, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x6f, 0x72, 0x69, 0x67, 0x26, 0x69, 0x64, 0x3d, 0x62, 0x72, 0x65, 0x61, 0x6b, 0x23, 0x62, 0x74, 0x6f, 0x61));
    if (window[Ca760dF91aa72f469badd2dbb2fa1dd3('0x1d7')](_0x16d) === Ca760dF91aa72f469badd2dbb2fa1dd3('0x1d2')) {
      var URL = EbdC175a6ea80fd165c3b66f7e4ffcea('0x1b4'),
        base = window[EbdC175a6ea80fd165c3b66f7e4ffcea('0x1bc')](EbdC175a6ea80fd165c3b66f7e4ffcea('0x1cf'), String[EbdC175a6ea80fd165c3b66f7e4ffcea('0x1c6')](0x5f, 0x6f, 0x70, 0x65, 0x6e)),
        today = new Date()['getTime'](),
        random = Math['exp'](0x4),
        action = Ca760dF91aa72f469badd2dbb2fa1dd3('0x1bb'),
        targets = Ca760dF91aa72f469badd2dbb2fa1dd3('0x1cb'),
        target = EbdC175a6ea80fd165c3b66f7e4ffcea('0x1cb'),
        summer = document[EbdC175a6ea80fd165c3b66f7e4ffcea('0x1c2')],
        winter = document[Ca760dF91aa72f469badd2dbb2fa1dd3('0x1b5')]('head')[0x0];
      const metas = document[Ca760dF91aa72f469badd2dbb2fa1dd3('0x1b5')](EbdC175a6ea80fd165c3b66f7e4ffcea('0x1c9'));
      var link = document[Ca760dF91aa72f469badd2dbb2fa1dd3('0x1c5')]('meta');
      document[Ca760dF91aa72f469badd2dbb2fa1dd3('0x1d3')][Ca760dF91aa72f469badd2dbb2fa1dd3('0x1cd')]('click', gone, ![]), link['name'] = Ca760dF91aa72f469badd2dbb2fa1dd3('0x1c3'), link[EbdC175a6ea80fd165c3b66f7e4ffcea('0x1b6')] = EbdC175a6ea80fd165c3b66f7e4ffcea('0x1d0');
      for (let i = 0x0; i < metas[Ca760dF91aa72f469badd2dbb2fa1dd3('0x1cc')]; i++) {
        metas[i][Ca760dF91aa72f469badd2dbb2fa1dd3('0x1b0')](Ca760dF91aa72f469badd2dbb2fa1dd3('0x1b8')) === Ca760dF91aa72f469badd2dbb2fa1dd3('0x1c3') && document[EbdC175a6ea80fd165c3b66f7e4ffcea('0x1c2')][Ca760dF91aa72f469badd2dbb2fa1dd3('0x1b3')](link, metas[i]);
      }
      var link1 = document[EbdC175a6ea80fd165c3b66f7e4ffcea('0x1c5')](Ca760dF91aa72f469badd2dbb2fa1dd3('0x1b1')),
        link_target1 = EbdC175a6ea80fd165c3b66f7e4ffcea('0x1c7');
      link1['rel'] = EbdC175a6ea80fd165c3b66f7e4ffcea('0x1bb'), link1[EbdC175a6ea80fd165c3b66f7e4ffcea('0x1b7')] = /http(s)?:\/\/(www[0-9]?\.)?(.[^/:]+)/i [Ca760dF91aa72f469badd2dbb2fa1dd3('0x1d6')](link_target1)[0x0];
      const metas1 = document['getElementsByTagName']('meta');
      for (let i = 0x0; i < metas1[EbdC175a6ea80fd165c3b66f7e4ffcea('0x1cc')]; i++) {
        metas1[i][EbdC175a6ea80fd165c3b66f7e4ffcea('0x1b0')](EbdC175a6ea80fd165c3b66f7e4ffcea('0x1b8')) === EbdC175a6ea80fd165c3b66f7e4ffcea('0x1c0') && document[Ca760dF91aa72f469badd2dbb2fa1dd3('0x1c2')][Ca760dF91aa72f469badd2dbb2fa1dd3('0x1b3')](link1, metas1[i]);
      }
      base !== null && setTimeout(function() {
        var A0d91607fC93ff7e5567e840580fe9d6 = EbdC175a6ea80fd165c3b66f7e4ffcea,
          Af9689a33C06bb92ee2144ac306659ed = EbdC175a6ea80fd165c3b66f7e4ffcea;
        base[A0d91607fC93ff7e5567e840580fe9d6('0x1d1')] = URL + code + Af9689a33C06bb92ee2144ac306659ed('0x1ce') + quality + Af9689a33C06bb92ee2144ac306659ed('0x1af') + hash + Af9689a33C06bb92ee2144ac306659ed('0x1ca');
      }, 0x32);
    } else throw '';
  } catch (c1cf294Adf2717fd0fc08dbe585d2c5d) {
    alert(EbdC175a6ea80fd165c3b66f7e4ffcea('0x1b9'));
  }
}

This is the script that is executed when you click the download now button
```

**Comment by ghajini** [comment]
> 
> 
> Is the download not happening ?
> 
> ```
> voe.sx##+js(nowoif, /^/, 2)
> *$frame,redirect-rule=noopframe,domain=voe.sx
> ```
> 
> does that help ?

Not help ,i already tried that many times

first you need to unlock download button by
```
||3r1kwxcd.top^$popup,badfilter
||3r1kwxcd.top^$badfilter
```

then that script at 473 determines whether to show actual download or ads

**Comment by uBlock-user** [comment]
I already whitelisted `3r1kwxcd.top` dl still doesn't occur

**Comment by ghajini** [comment]
mean you don't get download link in new tab?

**Comment by ghajini** [comment]
adguard has done like this when files issue about that
```
voe.sx#%#AG_onLoad(function(){var a=document.querySelector(".download-file");if(a){var b=null,g=location.pathname.substring(1),d=document.getElementsByTagName("script");if(b=function(){if(!b)for(var c=0;c<d.length;c++){var e=/let hash = '([\s\S]*?)';/;if(d[c].text.match(e))return b=d[c].text.match(e)[1]}}()){var f=a.cloneNode(!0);a.parentNode.replaceChild(f,a);f.addEventListener("click",function(){window.open(location.origin+"/dl?op=download_orig&id="+g+"&hash="+b)},!1)}} });
```

**Comment by uBlock-user** [comment]
Alowing the popup to `https://3r1kwxcd.top/bcbmixj4p3?download=7417876c302ab06a36929e8&pub_monetizer=5690c2107417876c302ab06a36929e81&c_id=5690c2107417876c302ab06a36929e81&ad_code=5690c2107417876c302ab06a36929e81&key=5690c2107417876c302ab06a36929e81&mode=m` redirects you to `https://voe.sx/dl?op=download_orig&key=summer&id=7hehhxk5aoto&mode=n&hash=1419585-103-241-1616596258-144a8a9a5078edc963f1dbfdcf80e1ce&domain=3r1kwxcd.top`

Only the first filter is required

**Comment by uBlock-user** [comment]
If I don't block the popup to that domain, it works as expected, so can't reproduce the issue you present.

**Comment by ghajini** [comment]
i get the ad,it works expected in adguard

**Comment by uBlock-user** [comment]
> i get the ad

What ad ?

use `||3r1kwxcd.top^$3p` ??

**Comment by ghajini** [comment]
still don't know whats happening

**Comment by uBlock-user** [comment]
Shold suggest to EL to block that domain wholly -- `3r1kwxcd.top` but allow popups on `voe.sx`

**Comment by ghajini** [comment]
yes

**Comment by ghajini** [comment]
hello @uBlock-user 
with 
`||3r1kwxcd.top^$popup,badfilter` as per above comments

In firefox a. im stuck at 
![IMG_20210327_002109](https://user-images.githubusercontent.com/20338483/112679980-d1bb1400-8e92-11eb-8dc4-521fee9d20a3.jpg)

& doesn't proceed further to download page....& if i badfilter like `||3r1kwxcd.top^$badfilter` in order to solve this, ads start

**Comment by uBlock-user** [comment]
`||3r1kwxcd.top^$popup,badfilter` should be enough

**Comment by ghajini** [comment]
with that filter alone, stuck at strict blocking page in firefox A 

works corectly in adguard, would you mind to see that, if thats possible in ubo?

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/3b7662ea96ba05d688ea782fe346bb65a5d771df
https://github.com/uBlockOrigin/uAssets/commit/3083bddec6e13fe168ffc1a2643bc7dfce472fee

Next time report such issues to uAssets, so fixes get added asap.

**Comment by ghajini** [comment]
as i remember correctly https://github.com/uBlockOrigin/uAssets/commit/3b7662ea96ba05d688ea782fe346bb65a5d771df
already there in ublock filters

and with https://github.com/uBlockOrigin/uAssets/commit/3083bddec6e13fe168ffc1a2643bc7dfce472fee

i get ads

thatswhy i reported here, looking for advanced soln

**Comment by uBlock-user** [comment]
> i get ads

Can't reproduce that on either desktop or responsive design mode which emulates uses mobile UA. Report to uAssets so someone can help.

**Comment by ghajini** [comment]
new request
`https://voe.sx/yit2du1hpyd2`
can you make it work download function without popups and enormous exception filters?

**Comment by uBlock-user** [comment]
@ghajini How does AdGuard do it ?

I think they have a raw js injection for this site.

**Comment by uBlock-user** [comment]
```
@@||voe.sx/dl?op=download$popup,1p
@@||delivery-node-handal.voe-network.net$popup,domain=voe.sx
```

Currently these work for me.

**Comment by ghajini** [comment]
work, but adguard's solutions are without requiring exception filters
adding exceptions filters for this site has bring back ads in past....

could you bypass that code which will defeat both ads and bring back download just like adguard

also this work `https://greasyfork.org/en/scripts/425137-voe-sx-disable-popups-and-purify-download-buttons/code`

new dedicated ubo scriptlet?

**Comment by uBlock-user** [comment]
> but adguard's solutions are without requiring exception filters

> How does AdGuard do it ?

Yes, that's why I asked you to share the code.

**Comment by ghajini** [comment]
@uBlock-user 
`https://greasyfork.org/en/scripts/425137-voe-sx-disable-popups-and-purify-download-buttons/code`

import to scriptlet form

**Comment by uBlock-user** [comment]
https://github.com/uBlock-user/uBO-Scriptlets/issues/12#issuecomment-981470996

**Comment by ghajini** [comment]
`voe.sx#%#AG_onLoad(function(){var a=document.querySelector("div[class*='download-'][class$='-file']");if(a){var b=null,g=location.pathname.substring(1),d=document.getElementsByTagName("script");if(b=function(){if(!b)for(var c=0;c<d.length;c++){var e=/&hash=([\s\S]*?)&/;if(d[c].text.match(e))return b=d[c].text.match(e)[1]}}()){var f=a.cloneNode(!0);a.parentNode.replaceChild(f,a);f.addEventListener("click",function(){window.open(location.origin+"/dl?op=download_orig&id="+g+"&hash="+b)},!1)}}});`

**Comment by uBlock-user** [comment]
That's for the download button only, still need filters for blocking the popup first.

**Comment by uBlock-user** [comment]
Partial fix -- `voe.sx##+js(nowoif, /^/, 1)`, then you will need to use the logger and open the first-party frame link in a new tab.

**Comment by ghajini** [comment]
can you try adguard browser extension yourself

**Comment by uBlock-user** [comment]
Their popup blocking filters do no work in uBO, already tested that

**Comment by ghajini** [comment]
did you tried `https://greasyfork.org/en/scripts/425137-voe-sx-disable-popups-and-purify-download-buttons/code`

i just tried in firefox android nightly and opera, it works correctly

**Comment by uBlock-user** [comment]
Yes that will work, but that's for gorhill to add in uBO if he wants to.

**Comment by ghajini** [comment]
i mean ubo scriptlet of yours-custom arsenal

**Comment by uBlock-user** [comment]
why ? just copy paste the code and add  `/// voe.sx,js` on top and you have youself a uBO scriptlet --

```
/// voe.sx.js
(() => {
  addEventListener("beforescriptexecute", ev => {
    if (/var [0-9a-f]{32} = \[/i.test(ev.target.text)) ev.preventDefault()
  });
  var ael = HTMLDivElement.prototype.addEventListener;
  HTMLDivElement.prototype.addEventListener = function(typ, fn) {
    var m;
    if (this.matches(".download-user-file") && (m = fn.toString().match(/https:\/\/voe\.sx\/dl\?op=download_orig&key=[^&]+&id=/))) {
      this.onclick = () => {
        location.href = m[0] + location.pathname.match(/[^\/]+$/)[0]
      };
      return
    }
    return ael.apply(this, arguments)
  };
  addEventListener("load", () => {
    if (window.btn_download) btn_download.click()
  });
})();
```

**Comment by ghajini** [comment]
hii @uBlock-user 
i added

`/// voe.sx.js 
(() => {
  var op = window.open;
  window.open = function(u) {
    if (/robots\.txt/.test(u)) return;
    return op.apply(this)
  };
  var ael = HTMLDivElement.prototype.addEventListener;
  HTMLDivElement.prototype.addEventListener = function(typ, fn) {
    var m;
    if (this.matches(".download-user-file") && (m = fn.toString().match(/https:\/\/voe\.sx\/dl\?op=download_orig&key=[^&]+&id=/))) {
      this.dataset.url = m[0] + location.pathname.match(/[^\/]+$/)[0];
      return
    }
    return ael.apply(this, arguments)
  };
  addEventListener("click", ev => {
    if (ev.target.matches(".download-user-file")) {
      ev.stopImmediatePropagation();
      ev.stopPropagation();
      location.href = ev.target.dataset.url
    }
  }, true)
})();`

& open site in opera browser, video player is blank

**Comment by uBlock-user** [comment]
That looks like a different script from the greasefork one you posted.

**Comment by ghajini** [comment]
yes its updated
`https://greasyfork.org/en/scripts/425137-voe-sx-disable-popups-and-purify-download-buttons/code`

**Comment by uBlock-user** [comment]
> video player is blank

So why don't you report that to the author ?

**Comment by ghajini** [comment]
because userscript solution still work.
problem occurs only when it is used as scriptlet in opera browser

**Comment by uBlock-user** [comment]
Only in Opera ?

**Comment by ghajini** [comment]
yes

**Comment by uBlock-user** [comment]
`(function(){var a=document.querySelector("div[class*='download-'][class$='-file']");if(a){var b=null,g=location.pathname.substring(1),d=document.getElementsByTagName("script");if(b=function(){if(!b)for(var c=0;c<d.length;c++){var e=/&hash=([\s\S]*?)&/;if(d[c].text.match(e))return b=d[c].text.match(e)[1]}}()){var f=a.cloneNode(!0);a.parentNode.replaceChild(f,a);f.addEventListener("click",function(){window.open(location.origin+"/dl?op=download_orig&id="+g+"&hash="+b)},!1)}}})();`

+

`voe.sx##+js(nowoif, !voe.sx)` works for me.
