### ISSUE TITLE
Add description to ReadMe explaining custom scriptlets

### ISSUE THREAD

**Issue by yokoffing** [uBlock-user/uBO-Scriptlets#16]
Please provide description explaining what the custom scriptlets cover vs. what default uBO scriplets cover.

Thanks!

**Comment by uBlock-user** [comment]
I feel it might be a laborious task for task for me to undertake. Sorry.

**Comment by uBlock-user** [comment]
If I were to summarise, whatever scriptlets that are not present in uBO  what I think deserve to be added for my use.
