### ISSUE TITLE
Twitch freezing constantly.

### ISSUE THREAD

**Issue by Hellements** [uBlock-user/uBO-Scriptlets#17]
Hello @uBlock-user 
I recently installed your uBO-Scriplets following a recommendation from yokoffing page: https://github.com/yokoffing/filterlists and noticed that it also "remove ads" from Twitch streams, which I really appreciate.
The problem is that when they play an ad, sometimes the video freezes, or it loops play-pause nonstop.
I use Win10pro 21H2 and Firefox 98.0 with uBlock Origin with those recommendations posted before.
I'm not sure if you are using the code from saucettv VideoAdBlockForTwitch found here: https://github.com/saucettv/VideoAdBlockForTwitch/blob/main/firefox/content.js but I see some resemblance between them (I'm not a coder).
My question is, could you update your scriplet maybe using the saucettv code as base since it's being periodically updated and works fine (Firefox Add-on), which I prefer, or make a version of the scriplet without the Twitch portion, so I can use the saucettv add-on, and they don't conflict with each other, please?
I hope I was clear enough (English is not my main language).
Thank you in advance.

**Comment by uBlock-user** [comment]
>  which I prefer, or make a version of the scriplet without the Twitch portion, so I can use the saucettv add-on

Add `twitch.tv#@#+js(twitch-videoad)` to my filters.

**Comment by Hellements** [comment]
Hello again @uBlock-user 
Thank you for your reply. I really don't know how to add that line to your filter. Also, when I set userResourcesLocation with https://raw.githubusercontent.com/uBlock-user/uBO-Scriptlets/master/scriptlets.js it will load your scriplet, if I'm not wrong.
For now, I can only clear userResourcesLocation and use saucettv add-on and hope you can upgrade your scriplet when possible, so I can put it back on.
Thank you.

**Comment by uBlock-user** [comment]
There's nothing to upgrade, you must make a choice. Either add the filter I posted above which will disable usage of my twitch scriptlet present or disable saucettv addon. Conflicts occur when you use both which is also explained by saucettv himself -- 

"You must remove any Twitch related user-scripts or other Twitch specific ad block extensions to prevent conflicts. You can use this extension with uBlock Origin though (Without user-scripts installed)."

**Comment by Hellements** [comment]
I'm not using them together (your scriplet + saucettv add-on). The reason I opened this thread is that the Twitch streams are often freezing or getting on play/pause loop, as said before. I cited saucettv add-on to maybe be used as a base or idea to improve/fix the Twitch portion on your scriplet, if you are using it or not, of course is your decision. That's why I said I'll be waiting for a fix/update to solve the issues.
Sorry if I was not clear enough previously. I hope you can understand now.
Thanks.

**Comment by uBlock-user** [comment]
> are often freezing or getting on play/pause loop

I can't reproduce it. If it's lag, report it to browser devs.

**Comment by uBlock-user** [comment]
>  that the Twitch streams are often freezing or getting on play/pause loop, as said before.

I can't reproduce this issue with only uBO installed.
