### ISSUE TITLE
element-replacer-onload replaces element by `noop` node?

### ISSUE THREAD

**Issue by gwarser** [uBlock-user/uBO-Scriptlets#3]
https://github.com/uBlock-user/uBO-Scriptlets/blob/eb4b020cd665ec73f7de34eddd41e71a08054999/scriptlets.txt#L395

```js
	let div = document.createElement('div');
	let replace = function() {
		let elements = document.querySelectorAll(selector);
		for ( let element of elements ) {
		      element.replaceWith(noop);
		}      
};
```

This may work because [replaceWith](https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/replaceWith) accepts strings.

***

This is not even string... :question:

**Comment by uBlock-user** [comment]
That was dumb mistake not to change noop to div at that line when I made the change in the first place. Thanks for noticing

**Comment by gwarser** [comment]
https://old.reddit.com/r/uBlockOrigin/comments/b86bs6/help_needed_with_scriptlet_for_replacing_html/
