### ISSUE TITLE
wiki request

### ISSUE THREAD

**Issue by bogachenko** [uBlock-user/uBO-Scriptlets#4]
How about spending time and creating something like this for your repository?
`https://github.com/gorhill/uBlock/wiki/Resources-Library`

Don't think about yourself when you read this, for you it will be useless, **but** not for people who do not know / know bad JS.

Well. Need a little: A brief description, how to use, an example. That's all.

**Comment by uBlock-user** [comment]
Good point, but I'm way too lazy to spend time on this, not to mention I only keep scriptlets that I found to have a single use ever, otherwise I will delete them myself, and if I have a wiki, then I will to spend time on maintaining it, not to mention I already maintain the uBO and uMatrix trackers, so this adds up to my list of responsibilities along with real life chores.

**Comment by uBlock-user** [comment]
> A brief description, how to use, an example.

Which scriptlet do you need this help specifically ?

**Comment by bogachenko** [comment]
I have a lot of issues, **articulate long and almost every**. Most of them are clear to me, but I don't know how to use them.Many of them are funny+stupid, but I don't know JS, but their names are clear, for which they are responsible too, but questions about markup are not clear.




It won't take long if 
```
A brief description, how to use, an example.
```
it is minimized. If we limit ourselves to just an example?
```
# cookie-setter
cookie-set.js application/javascript
```
between these terms briefly write how to use it


eg

```
# cookie-setter
# google.com##+js(cookie-set.js, shit; 20190910; path=/;)
cookie-set.js application/javascript
```

**Comment by uBlock-user** [comment]
> why do you delete the scriptlets,

If I'm deleting them, then I have a replacement in place already, don't worry about it.

> between these terms briefly write how to use it

eg

Doable. I will consider it nexttime.

**Comment by uBlock-user** [comment]
> what about if we limit ourselves to just an example? 

> between these terms briefly write how to use it

Done.

**Comment by bogachenko** [comment]
I see. Thank you very much. but I have 2 questions.

1. is it possible to make a script to delete not only inline frames and styles? (just a question, I myself do not sit on the left sites but it would be logical to add and not only inline)
2. It does not work for me `example.com##+js(autoplay-defuser.js)` I tried on `twitch.tv`, `youtube.com`, `kinopoisk.ru` (to trailers) and, and nothing

**Comment by uBlock-user** [comment]
> is it possible to make a script to delete not only inline frames and styles?

I do not understand the question.

> It does not work for me example.com##+js(autoplay-defuser.js) I tried on twitch.tv, youtube.com, kinopoisk.ru (to trailers) and, and nothing

Likely because of race condition OR because website is using autoplay inside an iframe like this -- `<iframe allow="autoplay;fullscreen"</iframe>` That's Feature Policy which is something that cannot be controlled  by one mere scriptlet.

**Comment by bogachenko** [comment]
I deleted it, wanted to rephrase, but you came before
Some sites use obfuscation. + url turns to porridge-base64
even if write regexp, they cannot be blocked by flags $frame $style coz they have similar url + equal length (a few letters different) but they have different contents. site yandex.ru used eg. so I ask, why not add a delete not only inline

ps crooked explained I hope you will understand

**Comment by uBlock-user** [comment]
> even if write regexp, they cannot be blocked by flags $frame $style coz they have similar url + equal length (a few letters different) but they have different contents. site yandex.ru used eg. so I ask, why not add a delete not only inline

I still don't understand, you can only remove inline tags which can be script, noscript, style and iframes. Post an example of an English website so I can see for myself.

**Comment by bogachenko** [comment]
>an English website

never mind. thanks anyway.

**Comment by bogachenko** [comment]
it's off topic
why don't you combine?


```js
# element-clicker
# example.com##+js(eclick.js, #example)
eclick.js application/javascript
(function() {
	let selector = '{{1}}';
	if ( selector === '' || selector === '{{1}}' ) {
		return;
	}
	let click = function() {
		let element = document.querySelector(selector);
		element.click();
	};
	if ( document.readyState === 'interactive' || document.readyState === 'complete' ) {
		click();
	} else {
		window.addEventListener('DOMContentLoaded', click);
	}
})();

# element-clicker-onload
# example.com##+js(eclick2.js, .example)
eclick2.js application/javascript
(function() {
         let selector = '{{1}}';
 		if ( selector === '' || selector === '{{1}}' ) {
        	return;
    	}
    	 let click = function() {
        	let element = document.querySelector(selector);
        	element.click();
        };
    	if (document.readyState === 'complete') {
        	click();
	} else {
        	window.addEventListener('load', click);
    	}
})();
```

**Comment by uBlock-user** [comment]
One runs on DOMContentLoaded and while the other runs on load, the load version is there incase DOMContentLoaded doesn't work.

**Comment by bogachenko** [comment]
> 
> 
> > even if write regexp, they cannot be blocked by flags $frame $style coz they have similar url + equal length (a few letters different) but they have different contents. site yandex.ru used eg. so I ask, why not add a delete not only inline
> 
> I still don't understand, you can only remove inline tags which can be script, noscript, style and iframes. Post an example of an English website so I can see for myself.



> 
> 
> > an English website
> 
> never mind. thanks anyway.


BTW, I found, not on the Russian sites such shit, as you requested

1. Chinese `91wii.com` site. Script - `https://static.mediav.com/js/mvf_g2.js` at the very bottom you can see `<frame>`
2. US `ebookdz.com` site. Sctipt - `http://ebookdz.com/forum/clientscript/vbulletin_md5.js` `var _0xd944` If you need to decrypt, here's a site for example `https://lelinhtinh.github.io/de4js/`

If the developer of this site adds something to this script, then this value will change `var _0xd944`.

In `var _0xd944` encrypted 2 script, 1 can be disabled as far as I know:
`ebookdz.com##+js(set-constant.js, String.prototype.charCodeAt, trueFunc)`

2, can not.

Well, to every time do not track the value of `var _0xd944`, can add Inline-scripts/frame/style/(a)other for all documents, that's what I meant.

**Comment by uBlock-user** [comment]
> Chinese 91wii.com site. Script - https://static.mediav.com/js/mvf_g2.js at the very bottom you can see <frame>
US ebookdz.com site. Sctipt - http://ebookdz.com/forum/clientscript/vbulletin_md5.js look in var _0xd944 there is <script>

The scriptlet I made is for removing inline styles/script/iframes in the root document. Not in the external javascripts. Since they're external javascripts, just block them with a blocking filter. Also why would the site dev beusing tags inside an external javascript is beyond me. It's invalid and those tags wouldn't work in the first place.

**Comment by bogachenko** [comment]
oh shit

**Comment by uBlock-user** [comment]
`91wii.com##+js(remove-inline-script.js, mvf_g2.js)` will remove the inline script tag itself from the DOM, so no connection will be made to static.mediav.com in the first place.

**Comment by bogachenko** [comment]
what about the second script. there are 2 scripts in 1. 1 can be will block on ez. 2 no.for nothing to cling to

**Comment by uBlock-user** [comment]
It seems, there's a race condition on that website, while I'm able to remove the inline script tag according to [DOM pane](https://i.gyazo.com/605ef0c6397a35b10c7948ae19f7e678.png), but a connection attempt still happens as per uBO which it blocks with `||mediav.com^$third-party` filter.

**Comment by bogachenko** [comment]
> what about the second script.
What second script ?

>US ebookdz.com site. Sctipt - http://ebookdz.com/forum/clientscript/vbulletin_md5.js look in var _0xd944 there is <script>

**Comment by uBlock-user** [comment]
Same as example 1, either remove it with my filter or go with a blockng filter if race condition interferes.

Also an fyi, all my remove-* scriptlets support Regex filtering. so you can use `/x|y|z/` as the value for filtering too.

**Comment by bogachenko** [comment]
hi. you can make regexp support for cookie-set.js

**Comment by uBlock-user** [comment]
Is there a use-case for that ? If so, post here.

**Comment by bogachenko** [comment]
@uBlock-user Dude, I remember you had a scriptlet that did the click function. For example, on the site there is a player whose div is a play, and you wrote the name of this div with this scriplet and the play appeared automatically. Do you have it? I cannot find it in history.

**Comment by uBlock-user** [comment]
@bogachenko found what exactly ?

**Comment by bogachenko** [comment]
@uBlock-user I found the scriptlet I mentioned above (strikethrough text)

**Comment by uBlock-user** [comment]
If they don't work on some sites you will need them to run on MutationObserver fyi, can't help you any further on that because I'm not going to spend time on those scriptlets that I don't deem relevant to me.

**Comment by bogachenko** [comment]
I did not ask you to help in finalizing this scriptlet, I asked you to find this scriptlet (but I found it myself).

Sorry to distract a serious person, will not happen again.
