### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by ghajini** [uBlock-user/uBO-Scriptlets#5]
Hello @uBlock-user
we want your feedback here
`https://github.com/uBlockOrigin/uAssets/issues/6163`

**Comment by uBlock-user** [comment]
Apparently I didn't get any github notifications at all even though mapx mentioned mentioned me twice or more.

**Comment by uBlock-user** [comment]
Nevermind, kulfoon has listed me in his blocklist on github, so I can't reply on his topics neither get any notifications.

**Comment by ghajini** [comment]
Forget what kulfoon did?
Is it possible to get direct URL
`https://kingsofteens.com/videos/1844/free-teen-sex-video-featuring-pretty-teenager-taylor-reed-stepsis-bliss.html`
from
`https://arda0hylt58g4wg0.pro/v2/a/skm/51786?tburl=https://kingsofteens.com/videos/1844/free-teen-sex-video-featuring-pretty-teenager-taylor-reed-stepsis-bliss.html`
Most of videos on that site are embedded in that garbage url `https://arda0hylt58g4wg0.pro` ,clicking on that videos doesn't get straight to URL but intervening ads(3rd party sites)

**Comment by uBlock-user** [comment]
I quickly wrote up an easier scriptlet for query-stripping because that RegEx version would be very difficult for filter formation --

```
qs.js application/javascript
(() => {
		'use strict';
		const query = '{{1}}';
		const querys = query.split(/\s*\|\s*/);
		const querystripper = ev => {
						if (ev) { window.removeEventListener(ev.type, querystripper, true); }
						const url = new URL(location);
						try {
							for (const querysremover of querys) {
								if (location.href.indexOf(querysremover + '=') !== -1) {
										url.searchParams.delete(query);
										window.location.href = url;
								}
							}	
						} catch (ex) { }		
		};
		if (document.readyState === 'loading') {
			 window.addEventListener('DOMContentLoaded', querystripper, true);
		} else {
			 querystripper();
		}

})();
```

> Is it possible to get direct URL
https://kingsofteens.com/videos/1844/free-teen-sex-video-featuring-pretty-teenager-taylor-reed-stepsis-bliss.html
from
https://arda0hylt58g4wg0.pro/v2/a/skm/51786?tburl=https://kingsofteens.com/videos/1844/free-teen-sex-video-featuring-pretty-teenager-taylor-reed-stepsis-bliss.html

Can't say, haven't seen this kind of case where the scummy URL is before the real URL.

**Comment by ghajini** [comment]
Yes that scummy URLs are present on many porn sites....

**Comment by uBlock-user** [comment]
It's present **before** the real URL that's the issue.

**Comment by ghajini** [comment]
So what's scriptlet format and what parameter to target in that site

https://github.com/uBlockOrigin/uAssets/issues/6163#issuecomment-525876859

**Comment by ghajini** [comment]
Problem is that
when you go to `kingsofteens.com` and click on any video,you don't get redirect to direct URL but garbage porn sites /3rd party sites......like I click on 7-8 times on video but I don't get direct URL. ...after some clicks it opens direct video URL. ....
Any help here will be helpfull👍

**Comment by uBlock-user** [comment]
This is the hyperlink -- https://kingsofteens.com/youngporn/out.php?s=65&l=vid&c=1&u=https://kingsofteens.com/videos/1844/free-teen-sex-video-featuring-pretty-teenager-taylor-reed-stepsis-bliss.html


and the link you want to go to is at the parameter &u=&u=https://kingsofteens.com/videos/1844/free-teen-sex-video-featuring-pretty-teenager-taylor-reed-stepsis-bliss.html


So it's not the main URL meaning query-stripper will not help here.

First you will have to extract the value of parameter u, then set window.location.href to u which will send you there. Complicated.

**Comment by uBlock-user** [comment]
> First you will have to extract the value of parameter u, then set window.location.href to u which will send you there. Complicated.


Scriptlet --

```
URL-extractor.js application/javascript
(() => {
		'use strict';
		const ue = ev => {
				    if (ev) { window.removeEventListener(ev.type, ue, true);}
				    try {
					    const url = new URL(location.href);
					    const params = new URLSearchParams(url.search.slice(1));
					    if (params.has('{{1}}')) {
						       const value = params.get('{{1}}');
						       window.location.href = value;
					    }
				    } catch (ex) { }
		};		    
		if (document.readyState === 'loading') {
			  window.addEventListener('DOMContentLoaded', ue, true);
	   	} else {
			  ue();
	   	}
})();
```

Will work as long as race condition is won in any individual run. YMMV.

**Comment by uBlock-user** [comment]
A better solution would be similar to how we dealt with `multiup.org` case.

**Comment by dumbusernameidk** [comment]
how do you make it so ubo can use custom scriptlets.

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uBlock-issues/wiki/Advanced-settings#userresourceslocation

**Comment by dumbusernameidk** [comment]
Tried it and it doesn't appear to work the filter `kingsofteens.com##+js(URL-extractor, u)` doesn't even show up only `kingsofteens.com##+js(ue.js` works. But the videos still open up junk websites.

**Comment by uBlock-user** [comment]
> Tried it and it doesn't appear to work the filter kingsofteens.com##+js(URL-extractor, u) doesn't even show up only kingsofteens.com##+js(ue.js works.

You made some mistake or you didn't update` https://raw.githubusercontent.com/uBlock-user/uBO-Scriptlets/master/scriptlets.txt` if you're using that. It only redirects you the url found in the parameter `u`.

> But the videos still open up junk websites.

> Will work as long as race condition is won in any individual run. YMMV.
