### ISSUE TITLE
multiup.org

### ISSUE THREAD

**Issue by ghajini** [uBlock-user/uBO-Scriptlets#6]
whats new solution for ads in

`https://multiup.org/en/mirror/951d7a0f87b2d9fa5843c21f37f5b5ae/ExtraMovies.wiki_CR19DAH72BRESD.mkv`

old solution no longer works
can you provide proper scriptlet filters for it

**Comment by uBlock-user** [comment]
Previous scriptlet works perfectly, no issues with links.

They added a notice which can be blocked with `multiup.org##.mfp-bg, .mfp-wrap`

**Comment by ghajini** [comment]
Going here
`https://multiup.org/en/mirror/61f077d52f836b16146483b614b80338/ExtraMovies.wiki_VB19S01E01.mkv`

Click 1fichier download, real download link iam not getting....

Expected result=
![Screenshot (177)](https://user-images.githubusercontent.com/20338483/69481259-c6d31800-0e35-11ea-854f-8c7856bc7c84.png)

Actual result =
![Screenshot (178)](https://user-images.githubusercontent.com/20338483/69481265-db171500-0e35-11ea-9072-e7f3a4f1b9f5.png)

**Comment by ghajini** [comment]
`https://multiup.org/en/mirror/6e283b441ff0c710848c8c0e63cd3062/ExtraMovies.wiki_BR49DAHE72BRESD.mkv?__cf_chl_jschl_tk__=a2e54335b8234033a9104cc29b074f1b17785179-1579204056-0-ATYtkbJPduSz7cu8IudrJG5Osf8g-SUmWaZw33B47j6jikS-iCAl5Vch84L8RiPI4oBesphHLMPx1mBYjictfOoXyomQZqqmBCw8yDCX751EtKghxR7fgCRoQ8DHhVX145nKmVLjqBcMH01GYoZ-KtclQtdMxG280_dnIx5IYhCm7edsRJpreaup5bpia6otn5QMJQvUXLExp5MDEMlVPBCgClkAPhCdq3HypIa08CrL2ShUrzfWUGyWZCGJLcnsuyWhhaaPK4hIczJ0SN2cMSccNfQFd3V2T0VmBQ10EPCzrroHH-kmuVaWrGakomk0O28uDxxRkBdciJV2zWZ4Nk892_JN5xF3KFso-OY7hOkOZUr0Asi-FXYVUrHVm4Mjkg`

With your scriptlet `multiup.org##+js(multiup, form[action], button[link])`
On downloading from filerio server page looks like this 
![IMG_20200117_011846](https://user-images.githubusercontent.com/20338483/72558225-475b4580-38c8-11ea-86c8-fe75eb52e10a.jpg)

ie without file info,download option

2. Actually it should look like this
![IMG_20200117_011914](https://user-images.githubusercontent.com/20338483/72558276-5e019c80-38c8-11ea-9e45-b7cb27125c91.jpg)


Can be checked on all browsers

**Comment by uBlock-user** [comment]
My filter doesn't apply on `filerio.in`, it applies on `multiup.org` domain only, so nothing to do with my filter.

**Comment by ghajini** [comment]
It is affecting file servers. Check with your filter.....
1chrck with download from 1fichier
It should look like this
![IMG_20200117_014718](https://user-images.githubusercontent.com/20338483/72559736-7fb05300-38cb-11ea-93d9-4a0a9eadce69.jpg)

 when clicked on download under 1fichier

But it looks like this 
![IMG_20200117_014646](https://user-images.githubusercontent.com/20338483/72559767-8dfe6f00-38cb-11ea-820f-db5155c7cfcb.jpg)

**Comment by ghajini** [comment]
You need to click download under filerio or 1fichier in this page 
`https://multiup.org/en/mirror/6e283b441ff0c710848c8c0e63cd3062/ExtraMovies.wiki_BR49DAHE72BRESD.mkv?__cf_chl_jschl_tk__=a2e54335b8234033a9104cc29b074f1b17785179-1579204056-0-ATYtkbJPduSz7cu8IudrJG5Osf8g-SUmWaZw33B47j6jikS-iCAl5Vch84L8RiPI4oBesphHLMPx1mBYjictfOoXyomQZqqmBCw8yDCX751EtKghxR7fgCRoQ8DHhVX145nKmVLjqBcMH01GYoZ-KtclQtdMxG280_dnIx5IYhCm7edsRJpreaup5bpia6otn5QMJQvUXLExp5MDEMlVPBCgClkAPhCdq3HypIa08CrL2ShUrzfWUGyWZCGJLcnsuyWhhaaPK4hIczJ0SN2cMSccNfQFd3V2T0VmBQ10EPCzrroHH-kmuVaWrGakomk0O28uDxxRkBdciJV2zWZ4Nk892_JN5xF3KFso-OY7hOkOZUr0Asi-FXYVUrHVm4Mjkg` 
in order to reproduce

**Comment by uBlock-user** [comment]
multiup makes a `POST` request instead of a `GET` request, that's why this happens. we discussed this on reddit months ago. My scriptlet filter only makes the buttons clickable. The problem is with the website itself.

**Comment by uBlock-user** [comment]
![image](https://user-images.githubusercontent.com/21290713/72562438-76c28000-38d1-11ea-899f-c1eb65c91675.png)

That's how it looks like with my scriptlet filter on desktop, I can't reproduce.

**Comment by ghajini** [comment]
Hello @uBlock-user ,
Did you check universal bypass solution for multiup.org and filesupload.org which is cleaner?

**Comment by uBlock-user** [comment]
> which is cleaner?

explain and elaborate on that

**Comment by ghajini** [comment]
I don't encounter these problems when using universal bypass with ubo
`https://github.com/uBlock-user/uBO-Scriptlets/issues/6#issuecomment-575319194`

`https://github.com/uBlock-user/uBO-Scriptlets/issues/6#issuecomment-575328892`

**Comment by uBlock-user** [comment]
https://addons.mozilla.org/en-US/firefox/addon/universal-bypass/ 

is that what you mean universal-bypass ?

**Comment by ghajini** [comment]
Yes
https://universal-bypass.org/install

**Comment by uBlock-user** [comment]
https://github.com/timmyRS/Universal-Bypass/issues/762#issuecomment-568247434

That's what they're doing. I merely replace the attribute value of "action" from the value of "link", they change the node from <button> to <a>(anchor tag).

**Comment by ghajini** [comment]
Also recently one of the other site started this multiup crap

`https://github.com/uBlockOrigin/uAssets/issues/4172#issuecomment-586137822`

I don't know why uassets contributors unable to reproduce/fix....

**Comment by uBlock-user** [comment]
> I don't know why uassets contributors/teams unable to reproduce/fix....

They can't because it requires making use of setAttribute function, which is something gorhill doesn't want to implement as it can be abused.

**Comment by ghajini** [comment]
> > I don't know why uassets contributors/teams unable to reproduce/fix....
> 
> They can't because it requires making use of setAttribute function, which is something gorhill doesn't want to implement



> > I don't know why uassets contributors/teams unable to reproduce/fix....
> 
> They can't because it requires making use of setAttribute function, which is something gorhill doesn't want to implement as it can be abused.

So letting ads pass through(every 4-5 website that multiup hosts)

**Comment by uBlock-user** [comment]
> So letting ads pass through(every 4-5 website that multiup hosts)?

I don't know what you mean. My scriptlet works and I have also posted the filter. As I told you before, my scriptlet causes no issues, the issue is how the server handles the request coming from a cellphone device, so in that case you can just use Universal Bypass. My scriptlet works as expected.

**Comment by ghajini** [comment]
I prefer to stick to ublock origin but certain issues, they don't fix😃

**Comment by uBlock-user** [comment]
Mostly because of lack of scriptlets, I have added those for my use.

**Comment by ghajini** [comment]
`https://multiup.org/en/mirror/1c28a3400eb447efb63e310b31ec4a0b/ExtraMovies.wiki_21B19FME72BRESD.mkv`

Did multiup scriptlet now work from yours?

`multiup.org##+js(multiup, form[action], button[link])`

**Comment by uBlock-user** [comment]
Yes, multiup.org##+js(multiup, form[action], button[link]) is now `multiup.org##+js(multiup, form[action], button[link], action, link)`

**Comment by ghajini** [comment]
Hey @uBlock-user 
I know the explanation given by you in this thread, last time you said in uassets repo about this issue that your solution  is exactly like a adguard snippet.
I just checked on adguard browser extension on firefox android for this site and no problems at all with filerio or 1fichier. ...... I got above discussed problems with your scriptlet....may be you revise (I know you explained clearly `https://github.com/uBlockOrigin/uAssets/issues/5435#issuecomment-611063369` but still things not work with your scriptlet but works with adguard solution . ..

If this seems still annoyable you can lock the thread😅

**Comment by uBlock-user** [comment]
> may be you revise

what can I revise ?

**Comment by ghajini** [comment]
Multiup Scriptlet to act like adguard if its based on adguard snippet

**Comment by uBlock-user** [comment]
It should, I don't know why it doesn't.

**Comment by ghajini** [comment]
opera browser stable ,latest ubo dev

1.
hello @uBlock-user 
here `https://multiup.org/en/mirror/9780755f3dfb317b2e5cc582419dfb4c/ExtraMovies.world%20-%20Wonder%20Woman%201984%20%282020%29%20IMAX%20720p%20HDRip%20English%20DD5.1%20x264%20AAC%20ESubs.mkv`

with your scriptlet `multiup.org##+js(multiup, form[action], button[link], action, link)` & all default ubo settings 

when i click on `download` under `filerio` lead me to 
![image](https://user-images.githubusercontent.com/20338483/103357015-30f9ca00-4ad8-11eb-85a0-6a238ef0efb4.png)

ie there is no download option 

expected behaviour= 
![image](https://user-images.githubusercontent.com/20338483/103357200-98b01500-4ad8-11eb-8530-05bf2de7071d.png)

2.
now with default ubo settings(ie w/o your scriptlet) and following violentmonkey script
```
// ==UserScript==
// @name        New script 
// @namespace   Violentmonkey Scripts
// @match       *://multiup.*/*
// @grant       none
// @version     1.0
// @author      -
// @description 4/13/2020, 6:04:59 AM
// ==/UserScript==

document.querySelectorAll("form>button[link]").forEach(b => {
  b.addEventListener("click", ev => {
    ev.preventDefault();
    location.href = b.getAttribute("link");
  }, true);
})
```

i see what a expected result look like

i really need to use your scriptlet working in firefox A(limited extension support) and opera browser stable

**Comment by uBlock-user** [comment]
Add `multiup.org##+js(sa, method, GET, form[method="POST"][action^="https://filerio.in/"][rel="noopener noreferrer nofollow"])` and report back.

**Comment by ghajini** [comment]
now that work
also 1fichier problem here `https://multiup.org/en/mirror/a116e1af65f258c0ec8a8eeef623b520/G2CSKMHD%20%282020%29%20www.SkymoviesHD.vin%20720p%20HEVC%20NF%20S03%20Complete%20Dual%20x265%20ESUb.mkv`

**Comment by uBlock-user** [comment]
`multiup.org##+js(sa, method, GET, form[method="POST"][action^="https://1fichier.com/"][rel="noopener noreferrer nofollow"])`

replace the URL in the action attribute for any other url where this happens.

**Comment by ghajini** [comment]
okay thanks i will check in firefox A if this work there ,opera i checked

**Comment by ghajini** [comment]
hey i created gist like this

`/// multiup.org.js
(() => {
document.querySelectorAll("form>button[link]").forEach(b => {
  b.addEventListener("click", ev => {
    ev.preventDefault();
    location.href = b.getAttribute("link");
  }, true);
});`
& added `multiup.org##+js(multiup.or.js)` & forced purge cache, filters, it doesn't work

url= `https://multiup.org/en/mirror/dc298527bce5d2631ce804ac13e3d39b/FAF9SKMHD%20%282021%29%20www.SkymoviesHD.sbs%201080p%20HEVC%20DC%20BluRay%20ORG%20Dual%20x265%20ESub.mkv`

**Comment by uBlock-user** [comment]
`multiup.org.js` or `multiup.or.js` ??

**Comment by ghajini** [comment]
a typo `multiup.org##+js(multiup.org.js)`

**Comment by uBlock-user** [comment]
why don't you just cop-paste the scriptlet and add a filter for it ?

**Comment by ghajini** [comment]
ah okay
