### ISSUE TITLE
upload.ac

### ISSUE THREAD

**Issue by ghajini** [uBlock-user/uBO-Scriptlets#7]
@uBlock-user 
Can your scriptlets be used to nullify `download with addons` button, that button seams to be malicious (https://github.com/uBlockOrigin/uAssets/issues/5340#issuecomment-575236636)

`upload.ac/n9qz9t33dp9c`

Ublock filter `upload.ac##+js(remove-attr, checked, #chkIsAdd)`
was used to be working but now it breaks basic download function on site

**Comment by uBlock-user** [comment]
That filter works just fine. They added a javascript which checks whether the download with addons button is checked or not and prevents the download from working if it's not checked. You can restore that filter if you have disabled/removed.

add `upload.ac##+js(acis, $, preventDefault)`

@mapx-

**Comment by mapx-** [comment]
we don't need anymore this filter
`upload.ac##+js(remove-attr, checked, #chkIsAdd)`

**Comment by uBlock-user** [comment]
Why not keep it ? It works just fine and still removes the tick.

**Comment by mapx-** [comment]
the tick is not active anymore

**Comment by uBlock-user** [comment]
Nevermind, with the filter I posted, tick or no tick, it no longer matters ;)

**Comment by mapx-** [comment]
Exactly
