### ISSUE TITLE
boost.ink

### ISSUE THREAD

**Issue by ghajini** [uBlock-user/uBO-Scriptlets#8]
Do you have any idea to bypass
`https://boost.ink/ia7o` via ubo scriptlets or yours

**Comment by uBlock-user** [comment]
Explain what it does and where did you find it ?

**Comment by ghajini** [comment]
Its a link shortener, where you have to click steps as given their ,after that proceed to target site button is visible just like
`https://github.com/uBlockOrigin/uAssets/issues/6065`

**Comment by uBlock-user** [comment]
`boost.ink##+js(disable-newtab-links)`

Click and wait for 2 secs, repeat untill all 4 are done.
