### ISSUE TITLE
Lankfiles.com

### ISSUE THREAD

**Issue by ghajini** [uBlock-user/uBO-Scriptlets#9]
Any possible fix/trick for this
@uBlock-user 

`https://github.com/uBlockOrigin/uAssets/issues/7593`

**Comment by uBlock-user** [comment]
No, because site never serves the download link, I get sent to ad-servers and some crapping domains on an endless redirect until Peter's list starts strict blocking such domains.

**Comment by uBlock-user** [comment]
Yes, websites asking you to fill offers/surveys and all that shit are by scummy by-design, some work, but this one doesn't.
